# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sugar_sdk/',
                'doc_host': 'https://velodrome-finance.github.io',
                'git_url': 'https://github.com/velodrome-finance/sugar-sdk/',
                'lib_path': 'sugar_sdk'},
  'syms': {'sugar_sdk.core': {'sugar_sdk.core.foo': ('core.html#foo', 'sugar_sdk/core.py')}}}
