# AUTOGENERATED! DO NOT EDIT! File to edit: ../src/web3.ipynb.

# %% auto 0
__all__ = ['w3']

# %% ../src/web3.ipynb 2
from web3 import AsyncWeb3, AsyncHTTPProvider
from .config import SugarConfig

# %% ../src/web3.ipynb 4
w3 = AsyncWeb3(AsyncHTTPProvider(SugarConfig.get_config().rpc_uri))
