# AUTOGENERATED! DO NOT EDIT! File to edit: ../src/web3.ipynb.

# %% auto 0
__all__ = ['w3', 'ADDRESS_ZERO', 'normalize_address']

# %% ../src/web3.ipynb 2
import os
from web3 import AsyncWeb3, AsyncHTTPProvider, Web3, constants

# %% ../src/web3.ipynb 4
w3 = AsyncWeb3(AsyncHTTPProvider(os.getenv("WEB3_PROVIDER_URI")))

def normalize_address(address: str) -> str: return Web3.to_checksum_address(address.lower())

ADDRESS_ZERO = constants.ADDRESS_ZERO
